_BASE_: mask2former_config.yaml
MODEL:
  META_ARCHITECTURE: "CLOUDS"
  SEM_SEG_HEAD:
    NAME: "CLOUDSHead"
    NUM_CLASSES: 19
  # backbone part.
  BACKBONE:
    NAME: "CLIP"
  WEIGHTS: "./clouds_cocopan.pth"
  PIXEL_MEAN: [122.7709383, 116.7460125, 104.09373615]
  PIXEL_STD: [68.5005327, 66.6321579, 70.32316305]
  CLOUDS:
    CLIP_MODEL_NAME: "convnext_large_d_320"
    CLIP_PRETRAINED_WEIGHTS: "laion2b_s29b_b131k_ft_soup"
    EMBED_DIM: 768
    GEOMETRIC_ENSEMBLE_ALPHA: 0.4
    GEOMETRIC_ENSEMBLE_BETA: 0.8
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 100
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OBJECT_MASK_THRESHOLD: 0.0

DATASETS:
  TRAIN: ("gta5",)

INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic_gta5"

DATALOADER:
  ASPECT_RATIO_GROUPING : False